### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by SeanNaren**
This PR contains a few improvement/refactors:

- Integrate variable lengths into the model
- Handle bug where at inference time batch size causes different output results from the model
- Fixed conv layer parameters
- Clean various compatibility code as well as use 3.5+ python os.makedirs function calls

This PR will make previous release models incompatible with the master branch, thus must use previous commit hashes given with the release to run them.

### CODE REVIEW

**Comment by miguelvr** [comment]
A couple of questions:

1) why did you ditch the plain `nn.DataParallel`?
2) Wouldn't it be better to keep the `device_ids` to choose what gpus to use?

**Comment by SeanNaren** [comment]
Hey @miguelvr! Thanks for the catch on device_ids. I'm removing DataParallel because as far as I'm concerned it's always better to use DistributedDataParallel, and instructions to do so as well as reasons are [here](https://github.com/SeanNaren/deepspeech.pytorch#multi-gpu-training).

**Comment by miguelvr** [comment]
why do you prefer multiproc over [pytorch's launch utility](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) ?

Is it possible to specify the GPU ids somehow with your implementation? To me, this is somewhat important as I don's always have all the GPUs in my cluster available to use.

**Comment by SeanNaren** [comment]
Mainly because the output is a [mess](https://github.com/pytorch/pytorch/issues/7134), hasn't been fixed just yet!

Sadly there isn't a way to do that via the multiproc script, you'd need to modify the multiproc script to point to the device_ids that you'd like to run the training process on. I can look into how to make this integrated into the script.

**Comment by miguelvr** [comment]
`DistributedDataParallel` has a `device_ids` parameter. I think it is possible to set this with the GPU rank. Maybe it's easier if we make use of an environment variable such as `CUDA_VISIBLE_DEVICES`?

I think it's a matter of defining the world size as the number of devices, and map the `gpu_rank` to the correct available `device_id`. Does this make any sense?

**Comment by SeanNaren** [comment]
@miguelvr this goes against the method of distribution that we've opted for; each GPU should be its own single process. The way for you to solve your case is via editing the `multiproc.py` file. The `train.py` file won't be aware of all the devices!

**Comment by miguelvr** [comment]
I was assuming, since you have: 

```
 model = torch.nn.parallel.DistributedDataParallel(model, device_ids=(int(args.gpu_rank),) if args.rank else None)
```

in `train.py` you could map the device_id of each process according to the list of available devices

**Comment by SeanNaren** [comment]
Pulling this in, I'll open a new issue to deal with this GPU availability problem @miguelvr

**Pull request merged**
