### PR TITLE
Using soundfile.read to include more than just .wav files

### PR DESCRIPTION
**Pull request by shamoons**
Resolves https://github.com/SeanNaren/deepspeech.pytorch/issues/495

### CODE REVIEW

**Comment by shamoons** [comment]
Can we merge this in?

**Comment by SeanNaren** [comment]
I'll need to ensure that this works with existing pre-trained models, i.e the audio features haven't changed

**Comment by shamoons** [comment]
Anything I can do to help that along?

**Comment by SeanNaren** [comment]
could you ensure that the pre-trained models get the same results on their corresponding datasets with and without this fix? maybe test wsj/an4?

**Comment by SeanNaren** [comment]
Made a few changes to ensure the output is the same, so doesn't break backwards compatibility!

**Pull request merged**
