### PR TITLE
Sox-based tempo/gain augmentation, Fix for ted/voxforge parsers for python2.7/3 compatibility, bidirectional command line flag flag

### PR DESCRIPTION
**Pull request by EgorLakomkin**
1. Here is a simple routine for real-time random utterance augmentation - apply a random change of tempo and gain during training to fight overfitting and increase model robustness. Tested on the combined training data of ted+libri+voxforge.
2. I also would propose to move to scipy's function of reading wav files as during my experiment librosa's load function sometimes introduced very strange delays.
3. In addition, I have added here a fix for python 2.7-3 compatibility for voxforge/ted loading.
4. And I have added 'bidirectional' flag if someone would want to have only forward rnn layers.

### CODE REVIEW

**Comment by SeanNaren** [comment]
Hey some cool stuff here thanks! Just a few pointers:

There is now an [audio](https://github.com/pytorch/audio) package that uses sox to load the audio. It may be wiser to use this than scipy's function, but I'm all up for discussion on that.
Has forward RNNs without a Row convolutional layer converged for you? I'd rather add this once row convolutions have been implemented (gives us forward context via an extra layer, more information in the Deepspeech paper). When we've done internal tests using the deepspeech.torch lua version, we needed to add a row convolution layer to see better validation results!

**Comment by EgorLakomkin** [comment]
Yeah, forward only model shows worse performance - I removed the flag.
That's great that there is pytorch/audio - I can quickly test it and use it instead of librosa/scipy for audio loading.

**Comment by EgorLakomkin** [comment]
I have pushed the version with using pytoch audio. I have tested on ~1k iterations and it is working good so far.

**Comment by SeanNaren** [comment]
Thanks man!

**Comment by loretoparisi** [comment]
@EgorLakomkin how to specify a sample rate like in `librosa.load` sr parameter? By defaults scipy `wavfile.read` will use 16000, while librosa 22050.

**Pull request merged**
