### PR TITLE
Feature/bugfix headless transcribe

### PR DESCRIPTION
**Pull request by la3lma**
Fixes bug "transcribe.py fails on startup in docker image when attempting to transcribe things #523"

### CODE REVIEW

**Comment by SeanNaren** [comment]
Thanks for this, do you mind doing a rebase to squash these commits into one?

**Comment by la3lma** [comment]
done

**Comment by SeanNaren** [comment]
Thank you!!

**Comment by la3lma** [comment]
You are welcome, and thank _you_  for this very nice software :-)

**Pull request merged**
