### PR TITLE
Add beam search

### PR DESCRIPTION
**Pull request by ryanleary**
This is a WIP integration of beam search based on my port of the ctc beam decoder in tensorflow. Will address #86. 

 Remaining:
- [x] additional testing
- [x] add optional dictionary constraint
- [x] add optional lm functionality
- [x] Add documentation
- [x] Update requirements.txt

If you want to test it out, you will need to manually install my pytorch_ctc bindings: https://github.com/ryanleary/pytorch-ctc

### CODE REVIEW

**Comment by ryanleary** [comment]
@SeanNaren - do you notice anything in here that would break training? I consistently get OOM errors during `clip_grad` in this branch for some reason. Cannot explain at the moment.

```
Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main()
  File "train.py", line 248, in main
    torch.nn.utils.clip_grad_norm(model.parameters(), args.max_norm)
File "/home/ryan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 25, in clip_grad_norm
    param_norm = p.grad.data.norm(norm_type)
RuntimeError: cuda runtime error (2) : out of memory at /py/conda-bld/pytorch_1493680494901/work/torch/lib/THC/THCGeneral.c:833
```

Perhaps something with the new BatchSoftmax layer? I've tried commenting out large swaths but it still seems to OOM.

**Comment by SeanNaren** [comment]
Hey man its definitely involving the new batch softmax layer i think, but the behaviour is really strange, will be digging a little further into it.

**Comment by ryanleary** [comment]
I was referencing pytorch/pytorch#1021 in the implementation of that module.

**Comment by ryanleary** [comment]
Fixed it. Accidentally omitted the final transform when in training mode.

**Comment by ryanleary** [comment]
Working through the kenlm integration now.

**Comment by willfrey** [comment]
FYI this is a thing.

https://github.com/timediv/tensorflow-with-kenlm

**Comment by SeanNaren** [comment]
@willfrey that's whats being merged

**Comment by ryanleary** [comment]
@SeanNaren it may be best to consider this experimental still, but I think it's probably safe to merge.

**Comment by SeanNaren** [comment]
Thanks a lot for this!

**Pull request merged**
