### PR TITLE
added samples TED and VoxForge datasets

### PR DESCRIPTION
**Pull request by EgorLakomkin**
Hello,

I have created a simple script that downloads and parses TEDLIUM v2 dataset from http://www.openslr.org/resources/19/TEDLIUM_release2.tar.gz and creates train/val/test manifests.

### CODE REVIEW

**Comment by EgorLakomkin** [comment]
Added samples from VoxForge also

**Comment by SeanNaren** [comment]
This is awesome thank you so much! I'll review this over the weekend

**Comment by EgorLakomkin** [comment]
Thank you for this great repo and your work!

**Comment by SeanNaren** [comment]
Thanks @EgorLakomkin :) I've pushed a few changes to refactor some of the code, let me know if anything is too far out from what you were going for! The Voxforge script is giving me strange errors when untaring the files after download. Will investigate further!

**Comment by EgorLakomkin** [comment]
@SeanNaren thank you for refactoring the code, looks great!

**Comment by francoishernandez** [comment]
Hi all,
Has anyone had the opportunity to run a training on the TED-LIUM v2 data? If so, what kind of WER did you reach?
Thanks in advance!
F

**Comment by SeanNaren** [comment]
@francoishernandez blocked currently to train this (waiting on availability of hardware) hopefully will train soon!

**Comment by francoishernandez** [comment]
Ok great, keep us posted!

**Pull request merged**
